/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Error: typeof import('./src/components/Error.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RocketCard: typeof import('./src/components/RocketCard.vue')['default']
    RocketForm: typeof import('./src/components/RocketForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SkeletonLoader: typeof import('./src/components/SkeletonLoader.vue')['default']
  }
}
